export const clerkLocalizations = {
  ru: {
    locale: "ru-RU",
    socialButtonsBlockButton: "Продолжить через {{provider|titleize}}",
    dividerText: "или",
    formFieldLabel__emailAddress: "Эл. почта",
    formFieldLabel__emailAddress_username: "Почта или логин",
    formFieldLabel__password: "Пароль",
    formFieldLabel__firstName: "Имя",
    formFieldLabel__lastName: "Фамилия",
    formFieldInputPlaceholder__emailAddress: "name@example.com",
    formFieldInputPlaceholder__emailAddress_username: "Почта или логин",
    formFieldInputPlaceholder__password: "Введите пароль",
    formFieldAction__forgotPassword: "Забыли пароль?",
    formButtonPrimary: "Продолжить",
    signInEnterPasswordTitle: "Введите пароль",
    backButton: "Назад",
    footerActionLink__useAnotherMethod: "Выбрать другой способ",
    signIn: {
      start: {
        title: "Войти",
        titleCombined: "Войти или зарегистрироваться",
        subtitle: "Используйте почту, чтобы продолжить.",
        subtitleCombined: "Используйте почту, чтобы продолжить.",
        actionText: "Нет аккаунта?",
        actionLink: "Зарегистрироваться",
      },
      password: {
        title: "Введите пароль",
        subtitle: "Продолжите вход в аккаунт.",
        actionLink: "Другой способ",
      },
      forgotPassword: {
        title: "Восстановление пароля",
        subtitle: "Мы отправим код для восстановления.",
        subtitle_email: "Мы отправим код на вашу почту.",
        formTitle: "Код восстановления",
        resendButton: "Отправить еще раз",
      },
      emailCode: {
        title: "Проверьте почту",
        subtitle: "Введите код из письма.",
        formTitle: "Код подтверждения",
        resendButton: "Отправить еще раз",
      },
    },
    signUp: {
      start: {
        title: "Регистрация",
        titleCombined: "Создайте аккаунт",
        subtitle: "Укажите почту, чтобы начать.",
        subtitleCombined: "Укажите почту, чтобы начать.",
        actionText: "Уже есть аккаунт?",
        actionLink: "Войти",
      },
      continue: {
        title: "Завершите регистрацию",
        subtitle: "Заполните оставшиеся поля.",
        actionText: "Уже есть аккаунт?",
        actionLink: "Войти",
      },
      emailCode: {
        title: "Проверьте почту",
        subtitle: "Введите код из письма.",
        formTitle: "Код подтверждения",
        formSubtitle: "Код отправлен на вашу почту.",
        resendButton: "Отправить еще раз",
      },
    },
  },
  kk: {
    locale: "kk-KZ",
    socialButtonsBlockButton: "{{provider|titleize}} арқылы жалғастыру",
    dividerText: "немесе",
    formFieldLabel__emailAddress: "Эл. пошта",
    formFieldLabel__emailAddress_username: "Пошта немесе логин",
    formFieldLabel__password: "Құпиясөз",
    formFieldLabel__firstName: "Аты",
    formFieldLabel__lastName: "Тегі",
    formFieldInputPlaceholder__emailAddress: "name@example.com",
    formFieldInputPlaceholder__emailAddress_username: "Пошта немесе логин",
    formFieldInputPlaceholder__password: "Құпиясөзді енгізіңіз",
    formFieldAction__forgotPassword: "Құпиясөзді ұмыттыңыз ба?",
    formButtonPrimary: "Жалғастыру",
    signInEnterPasswordTitle: "Құпиясөзді енгізіңіз",
    backButton: "Артқа",
    footerActionLink__useAnotherMethod: "Басқа тәсілді таңдау",
    signIn: {
      start: {
        title: "Кіру",
        titleCombined: "Кіру немесе тіркелу",
        subtitle: "Жалғастыру үшін эл. поштаңызды қолданыңыз.",
        subtitleCombined: "Жалғастыру үшін эл. поштаңызды қолданыңыз.",
        actionText: "Аккаунтыңыз жоқ па?",
        actionLink: "Тіркелу",
      },
      password: {
        title: "Құпиясөзді енгізіңіз",
        subtitle: "Аккаунтқа кіруді жалғастырыңыз.",
        actionLink: "Басқа тәсіл",
      },
      forgotPassword: {
        title: "Құпиясөзді қалпына келтіру",
        subtitle: "Қалпына келтіру кодын жібереміз.",
        subtitle_email: "Код эл. поштаңызға жіберіледі.",
        formTitle: "Қалпына келтіру коды",
        resendButton: "Қайта жіберу",
      },
      emailCode: {
        title: "Поштаңызды тексеріңіз",
        subtitle: "Хаттағы кодты енгізіңіз.",
        formTitle: "Растау коды",
        resendButton: "Қайта жіберу",
      },
    },
    signUp: {
      start: {
        title: "Тіркелу",
        titleCombined: "Аккаунт ашу",
        subtitle: "Бастау үшін эл. поштаңызды енгізіңіз.",
        subtitleCombined: "Бастау үшін эл. поштаңызды енгізіңіз.",
        actionText: "Аккаунтыңыз бар ма?",
        actionLink: "Кіру",
      },
      continue: {
        title: "Тіркелуді аяқтаңыз",
        subtitle: "Қалған өрістерді толтырыңыз.",
        actionText: "Аккаунтыңыз бар ма?",
        actionLink: "Кіру",
      },
      emailCode: {
        title: "Поштаңызды тексеріңіз",
        subtitle: "Хаттағы кодты енгізіңіз.",
        formTitle: "Растау коды",
        formSubtitle: "Код эл. поштаңызға жіберілді.",
        resendButton: "Қайта жіберу",
      },
    },
  },
} as const;
